// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dts_challenge_backend.Data;

#nullable disable

namespace dts_challenge_backend.Data.Migrations
{
    [DbContext(typeof(CaseTasksDbContext))]
    [Migration("20260508211231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dts_challenge_backend.Data.CaseTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaseTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Update the court hearing schedule",
                            DueDate = new DateOnly(2026, 6, 10),
                            Status = 0,
                            Title = "Update Hearing Schedule"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DueDate = new DateOnly(2026, 5, 25),
                            Status = 1,
                            Title = "Sorting Evidence"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Review evidence in cae 00010",
                            DueDate = new DateOnly(2026, 5, 15),
                            Status = 2,
                            Title = "Review Evidence"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
